package com.unit.test

object benchmarkingSuitJsonIteratorBuilder {
//// Result for below operation when run once.
////    { "1test2":[,"2",],
////      "1 maptest":{1.0:{1.0:{1.0:1.0}}},
////      1.0:1.0,
////      "1_":1.0,
////      "1 arra_map":[{"1":1.0},2.0],
////      "1 maptest2":{  "1test2":[,"2",],
////                      1.0:1.0,
////                      "1_":1.0,
////                      "1test":[2.0,2.0,[[,"2",],"2",]],
////                      "1":"1"},
////      "1test":[2.0,2.0,[[,"2",],"2",]],
////      "1":"1"}
//
//    for(count <- List(1,10,100,1000,10000,100000)) {
//
//      println("testing with "+count+" elements")
//          val builder = new JsonIteratorBuilder(JsonPrototypeFactory.getInstance( new JsonObject(null), new JsonArray(Nil), new JsonNumber(0), new JsonString(null)))
//      builder.pushS()
//        Logger.timer(for(i <- 1 to count) {
//
//          builder.pushP()
//          builder.pushK(i.toString() + " arra_map")
//          builder.pushVA()
//          builder.pushA()
//          builder.pushVSS()
//          builder.pushS()
//          builder.pushP()
//          builder.pushK(i.toString())
//          builder.pushV(i)
//          builder.pushL()
//          builder.pushVSE()
//          builder.pushA()
//          builder.pushV(2)
//          builder.pushVAE()
//          builder.pushL()
//
//          builder.pushP()
//          builder.pushK(i.toString()+" maptest")
//          builder.pushVSS()
//          builder.pushS()
//          builder.pushP()
//          builder.pushK(i)
//          builder.pushVSS()
//          builder.pushS()
//          builder.pushP()
//          builder.pushK(i)
//          builder.pushVSS()
//          builder.pushS()
//          builder.pushP()
//          builder.pushK(i)
//          builder.pushV(i)
//          builder.pushL()
//          builder.pushVSE()
//          builder.pushL()
//          builder.pushVSE()
//          builder.pushL()
//          builder.pushVSE()
//          builder.pushL()
//          builder.pushP()
//          builder.pushK(i.toString()+" maptest2")
//          builder.pushVSS()
//          builder.pushS()
//          builder.pushP()
//          builder.pushK(i)
//          builder.pushV(i)
//          builder.pushL()
//          builder.pushP()
//
//          builder.pushK(i.toString())
//          builder.pushV(i.toString())
//          builder.pushL()
//          builder.pushP()
//          builder.pushK(i)
//          builder.pushV(i)
//          builder.pushL()
//          builder.pushP()
//          builder.pushK(i.toString()+"test")
//          builder.pushVA()
//          builder.pushA()
//          builder.pushV(2)
//          builder.pushA()
//          builder.pushV(2)
//          builder.pushA()
//          builder.pushVA()
//          builder.pushA()
//          builder.pushVA()
//          builder.pushA()
//          builder.pushV(null)
//          builder.pushA()
//          builder.pushV("2")
//          builder.pushA()
//          builder.pushV(null)
//          builder.pushVAE()
//          builder.pushA()
//          builder.pushV("2")
//          builder.pushA()
//          builder.pushV(null)
//          builder.pushVAE()
//          builder.pushVAE()
//          builder.pushL()
//          builder.pushP()
//          builder.pushK(i.toString()+"test2")
//          builder.pushVA()
//          builder.pushA()
//          builder.pushV(null)
//          builder.pushA()
//          builder.pushV("2")
//          builder.pushA()
//          builder.pushV(null)
//          builder.pushVAE()
//          builder.pushL()
//          builder.pushP()
//          builder.pushK(i.toString()+"_")
//          builder.pushV(i)
//
//
//          builder.pushL()
//          builder.pushVSE()
//          builder.pushL()
//
//
//          builder.pushP()
//          builder.pushK(i.toString())
//          builder.pushV(i.toString())
//          builder.pushL()
//          builder.pushP()
//          builder.pushK(i)
//          builder.pushV(i)
//          builder.pushL()
//          builder.pushP()
//          builder.pushK(i.toString()+"test")
//          builder.pushVA()
//          builder.pushA()
//          builder.pushV(2)
//          builder.pushA()
//          builder.pushV(2)
//          builder.pushA()
//          builder.pushVA()
//          builder.pushA()
//          builder.pushVA()
//          builder.pushA()
//          builder.pushV(null)
//          builder.pushA()
//          builder.pushV("2")
//          builder.pushA()
//          builder.pushV(null)
//          builder.pushVAE()
//          builder.pushA()
//          builder.pushV("2")
//          builder.pushA()
//          builder.pushV(null)
//          builder.pushVAE()
//          builder.pushVAE()
//          builder.pushL()
//          builder.pushP()
//          builder.pushK(i.toString()+"test2")
//          builder.pushVA()
//          builder.pushA()
//          builder.pushV(null)
//          builder.pushA()
//          builder.pushV("2")
//          builder.pushA()
//          builder.pushV(null)
//          builder.pushVAE()
//          builder.pushL()
//          builder.pushP()
//          builder.pushK(i.toString()+"_")
//          builder.pushV(i)
//          builder.pushL()
//
//
//        })
//
//      builder.pushVSE()
//      println("constrcution done")
//      val a = builder.build()
//
//    }

}